# Generated by Django 5.2.2 on 2025-08-30 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('maidenname', models.CharField(blank=True, max_length=100, null=True)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('civil_status', models.CharField(choices=[('Si', 'Single'), ('Se', 'Separated'), ('Co', 'Cohabitation (live-in)'), ('Ma', 'Married'), ('Wi', 'Widow/er')], max_length=40)),
                ('landline', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('educational_attainment', models.CharField(choices=[('No', 'None'), ('Ki', 'Kindergarten'), ('El', 'Elementary'), ('Jh', 'Junior High School'), ('Sh', 'Senior High School'), ('Co', 'College'), ('Vo', 'Vocational'), ('Po', 'Post Graduate')], max_length=30)),
                ('family_details', models.JSONField(default=dict)),
                ('profile_image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('apparent_disability', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3)),
                ('coordinates', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DisabilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=8)),
                ('registration_type', models.CharField(choices=[('Wa', 'Walk-in Application'), ('Ol', 'Online Application')], max_length=30)),
                ('accomplished_by', models.CharField(choices=[('Ap', 'Applicant'), ('Gu', 'Guardian'), ('Re', 'Representative')], max_length=30)),
                ('accomplished_by_name', models.CharField(max_length=100)),
                ('physician_name', models.CharField(blank=True, max_length=100, null=True)),
                ('physician_license_no', models.CharField(blank=True, max_length=50, null=True)),
                ('processing_officer', models.CharField(blank=True, max_length=100, null=True)),
                ('approving_officer', models.CharField(blank=True, max_length=100, null=True)),
                ('encoder', models.CharField(blank=True, max_length=100, null=True)),
                ('reporting_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('control_no', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Pending', max_length=15)),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField()),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=2, null=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.applicant')),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.barangay')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantDisability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_cause', models.CharField(choices=[('Inborn', 'Congenital/Inborn'), ('Acquired', 'Acquired')], max_length=30)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_disabilities', to='api.applicant')),
                ('disability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disability', to='api.disability')),
            ],
        ),
        migrations.AddField(
            model_name='disability',
            name='disability_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disabilities', to='api.disabilitytype'),
        ),
        migrations.CreateModel(
            name='IDReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sss_no', models.CharField(blank=True, max_length=50, null=True)),
                ('gsis_no', models.CharField(blank=True, max_length=50, null=True)),
                ('pagibig_no', models.CharField(blank=True, max_length=50, null=True)),
                ('psn_no', models.CharField(blank=True, max_length=50, null=True)),
                ('philhealth_no', models.CharField(blank=True, max_length=50, null=True)),
                ('other_id', models.CharField(blank=True, max_length=100, null=True)),
                ('other_id_no', models.CharField(blank=True, max_length=50, null=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation_name', models.CharField(max_length=255)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_status', models.CharField(choices=[('Em', 'Employed'), ('Un', 'Unemployed'), ('Se', 'Self-employed')], default='Em', max_length=15)),
                ('emp_category', models.CharField(choices=[('Go', 'Government'), ('Pr', 'Private')], default='Go', max_length=15)),
                ('emp_type', models.CharField(choices=[('Re', 'Permanent/Regular'), ('Se', 'Seasonal'), ('Ca', 'Casual'), ('Em', 'Emergency')], default='Re', max_length=50)),
                ('other_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.JSONField(blank=True, default=dict, null=True)),
                ('occupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.occupation')),
            ],
        ),
        migrations.CreateModel(
            name='PWD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inactive_reason', models.CharField(max_length=255)),
                ('date_died', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.application')),
            ],
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_message', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('pwd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pwd')),
            ],
        ),
    ]
