# Generated by Django 5.2.2 on 2025-06-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employment_occupation_address_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_type_name', models.CharField(max_length=50)),
            ],
        ),
    ]
