# Generated by Django 5.2.2 on 2025-06-21 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_disabilitytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sss_no', models.CharField(verbose_name=50)),
                ('gsis_no', models.CharField(verbose_name=50)),
                ('pagibig_no', models.CharField(verbose_name=50)),
                ('psn_no', models.CharField(verbose_name=50)),
                ('philhealth_no', models.CharField(verbose_name=50)),
                ('other_id', models.CharField(verbose_name=100)),
                ('other_id_no', models.CharField(verbose_name=50)),
            ],
        ),
        migrations.AddField(
            model_name='employment',
            name='emp_category',
            field=models.CharField(choices=[('Go', 'Government'), ('Pr', 'Private')], default='Go', max_length=15),
        ),
        migrations.AddField(
            model_name='employment',
            name='emp_status',
            field=models.CharField(choices=[('Em', 'Employed'), ('Un', 'Unemployed'), ('Se', 'Self-employed')], default='Em', max_length=15),
        ),
        migrations.AddField(
            model_name='employment',
            name='emp_type',
            field=models.CharField(choices=[('Re', 'Permanent/Regular'), ('Se', 'Seasonal'), ('Ca', 'Casual'), ('Em', 'Emergency')], default='Re', max_length=50),
        ),
        migrations.AddField(
            model_name='employment',
            name='occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.occupation'),
        ),
        migrations.AddField(
            model_name='employment',
            name='organization',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='employment',
            name='other_occupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('maidenname', models.CharField(blank=True, max_length=100, null=True)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('civil_status', models.CharField(choices=[('Si', 'Single'), ('Se', 'Separated'), ('Co', 'Cohabitation (live-in)'), ('Ma', 'Married'), ('Wi', 'Widow/er')], max_length=40)),
                ('landline', models.CharField(max_length=20, null=True)),
                ('mobile_no', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('educational_attainment', models.CharField(choices=[('No', 'None'), ('Ki', 'Kindergarten'), ('El', 'Elementary'), ('Jh', 'Junior High School'), ('Sh', 'Senior High School'), ('Co', 'College'), ('Vo', 'Vocational'), ('Po', 'Post Graduate')], max_length=30)),
                ('family_details', models.JSONField(default=dict)),
                ('profile_image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('apparent_disability', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3)),
                ('coordinates', models.JSONField(default=dict)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employment')),
                ('id_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.idreference')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=8)),
                ('registration_type', models.CharField(choices=[('Wa', 'Walk-in Application'), ('Ol', 'Online Application')], max_length=30)),
                ('accomplished_by', models.CharField(choices=[('Ap', 'Applicant'), ('Gu', 'Guardian'), ('Re', 'Representative')], max_length=30)),
                ('accomplished_by_name', models.CharField(max_length=100)),
                ('physician_name', models.CharField(max_length=100)),
                ('physician_license_no', models.CharField(max_length=50)),
                ('processing_officer', models.CharField(blank=True, max_length=100, null=True)),
                ('approving_officer', models.CharField(blank=True, max_length=100, null=True)),
                ('encoder', models.CharField(blank=True, max_length=100, null=True)),
                ('reporting_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('control_no', models.CharField(blank=True, max_length=50, null=True)),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_name', models.CharField(max_length=250)),
                ('disability_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disabilitytype')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantDisability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_cause', models.CharField(choices=[('Inborn', 'Congenital/Inborn'), ('Acquired', 'Acquired')], max_length=30)),
                ('disability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disability')),
            ],
        ),
    ]
