# Generated by Django 5.2.2 on 2025-06-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_idreference_employment_emp_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idreference',
            name='gsis_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='idreference',
            name='other_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='idreference',
            name='other_id_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='idreference',
            name='pagibig_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='idreference',
            name='philhealth_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='idreference',
            name='psn_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='idreference',
            name='sss_no',
            field=models.CharField(max_length=50),
        ),
    ]
