# Generated by Django 5.2.2 on 2025-07-16 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_idreference_gsis_no_alter_idreference_other_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.address'),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.applicant'),
        ),
    ]
