# Generated by Django 5.2.2 on 2025-07-17 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_applicant_address_alter_application_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdisability',
            name='applicant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.applicant'),
        ),
    ]
