# Generated by Django 5.2.2 on 2025-07-17 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_applicantdisability_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdisability',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_disabilities', to='api.applicant'),
        ),
    ]
