# Generated by Django 5.2.2 on 2025-07-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_applicant_email_alter_applicant_landline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pwdinfo',
            name='status',
        ),
        migrations.AlterField(
            model_name='pwdinfo',
            name='date_died',
            field=models.DateField(blank=True, null=True),
        ),
    ]
