# Generated by Django 5.2.2 on 2025-07-22 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_pwdinfo_status_alter_pwdinfo_date_died'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('pwd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pwdinfo')),
            ],
        ),
    ]
