# Generated by Django 5.2.2 on 2025-08-15 11:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_application_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='application',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
